import re
import os

topics_to_add = """
  // -- 1890s -------------------------------------------------------------
  {
    id: 'event-vivekananda-chicago-1893',
    decadeId: '1890s',
    year: 1893,
    startDate: '1893-09-11',
    endDate: '1893-09-27',
    title: 'Swami Vivekananda at Chicago',
    subtitle: "Parliament of the World's Religions",
    shortDescription: "Swami Vivekananda introduced Hinduism to the global stage at the Parliament of Religions.",
    fullDescription: "On September 11, 1893, Swami Vivekananda delivered his landmark speech in Chicago, addressing the audience as 'Sisters and Brothers of America'. This event is widely regarded as the introduction of Hinduism to the West and a pivotal moment in modern Indian cultural history.",
    era: '1893',
    dateDisplay: '11 SEP 1893',
    datePrecision: 'exact',
    chronologicalPosition: 1,
    journeyStage: 'Culture & philosophy',
    significance: "Established modern Vedanta philosophy globally and fostered a new cultural self-awareness in colonial India.",
    category: 'Philosophy & Culture',
    domain: 'Philosophy & Culture',
    relatedPeople: ['Swami Vivekananda'],
    relatedPlaces: ['Chicago', 'Bengal'],
    relatedCivilizationIds: [],
    relatedTopics: ['Ramakrishna Mission'],
    learningExperienceId: 'exp-vivekananda-chicago',
    region: 'Bengal / Global',
    geographicRegion: 'Bengal',
    location: 'Chicago, USA',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-vivekananda-chicago', title: 'Addresses at The Parliament of Religions', authorOrInstitution: 'Belur Math / Ramakrishna Mission', yearOrPeriod: '1893', sourceType: 'primary', confidence: 'verified', url: 'https://belurmath.org/swami-vivekananda-speeches-at-the-parliament-of-religions-chicago-1893/' }],
  },
  {
    id: 'event-epidemic-act-1897',
    decadeId: '1890s',
    year: 1897,
    startDate: '1897-02-04',
    title: 'The Epidemic Diseases Act, 1897',
    subtitle: 'Bubonic Plague in Bombay Presidency',
    shortDescription: 'The colonial government passed the Epidemic Diseases Act to control the devastating bubonic plague.',
    fullDescription: 'In response to the outbreak of the bubonic plague in Bombay, the British colonial government enacted the Epidemic Diseases Act of 1897. The harsh enforcement measures led to significant social unrest, notably the assassination of plague commissioner W.C. Rand by the Chapekar brothers in Pune.',
    era: '1897',
    dateDisplay: '04 FEB 1897',
    datePrecision: 'exact',
    chronologicalPosition: 2,
    journeyStage: 'Law & Society',
    significance: 'Provided sweeping powers for disease control; the act remained a cornerstone of Indian public health law for over a century.',
    category: 'Public Health & Law',
    domain: 'Public Health & Law',
    relatedPeople: ['W.C. Rand', 'Chapekar Brothers'],
    relatedPlaces: ['Bombay', 'Pune'],
    relatedCivilizationIds: [],
    relatedTopics: ['Colonial Law', 'Public Health'],
    learningExperienceId: 'exp-epidemic-act',
    region: 'Bombay Presidency',
    geographicRegion: 'Maharashtra',
    location: 'Bombay and Pune',
    immediateConsequences: 'Severe quarantine measures and social unrest in Pune.',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-epidemic-act', title: 'The Epidemic Diseases Act, 1897', authorOrInstitution: 'India Code', yearOrPeriod: '1897', sourceType: 'government_archive', confidence: 'verified', url: 'https://www.indiacode.nic.in/handle/123456789/2330' }],
  },
  {
    id: 'event-birsa-munda-1899',
    decadeId: '1890s',
    year: 1899,
    startDate: '1899-12-24',
    title: "Birsa Munda's Ulgulan",
    subtitle: 'The Great Tumult in Chotanagpur',
    shortDescription: 'Birsa Munda led a major tribal uprising against the British and exploitative landlords.',
    fullDescription: 'The Ulgulan (Great Tumult) was a tribal rebellion in the Chotanagpur region led by Birsa Munda. Driven by agrarian discontent over land alienation and the disruption of traditional Khuntkatti land systems by British authorities and dikus (outsiders), the movement sought to establish Munda Raj.',
    era: '1899',
    dateDisplay: '1899 - 1900',
    datePrecision: 'exact',
    chronologicalPosition: 3,
    journeyStage: 'Tribal Resistance',
    significance: 'Led to the Chota Nagpur Tenancy Act of 1908, restricting the transfer of tribal land to non-tribals.',
    category: 'Social & Political',
    domain: 'Social & Political',
    relatedPeople: ['Birsa Munda'],
    relatedPlaces: ['Ranchi', 'Khunti'],
    relatedCivilizationIds: [],
    relatedTopics: ['Tribal Movements'],
    learningExperienceId: 'exp-birsa-munda',
    region: 'Chotanagpur Plateau',
    geographicRegion: 'Jharkhand',
    location: 'Chotanagpur',
    longTermSignificance: 'Inspired future tribal rights movements and secured the Chota Nagpur Tenancy Act.',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-birsa-munda', title: 'Tribal Resistance Movements', authorOrInstitution: 'National Archives of India', yearOrPeriod: '1899', sourceType: 'government_archive', confidence: 'verified' }],
  },

  // -- 1940s -------------------------------------------------------------
  {
    id: 'event-rin-mutiny-1946',
    decadeId: '1940s',
    year: 1946,
    startDate: '1946-02-18',
    endDate: '1946-02-23',
    title: 'Royal Indian Navy Mutiny',
    subtitle: 'Naval Uprising in Bombay',
    shortDescription: 'Indian sailors of the Royal Indian Navy mutinied against British officers.',
    fullDescription: 'Starting on HMIS Talwar in Bombay, Indian sailors (ratings) of the Royal Indian Navy mutinied against poor conditions, racist treatment, and British rule. The revolt rapidly spread to ships and shore establishments across Karachi, Madras, and Calcutta, heavily undermining British military authority.',
    era: '1946',
    dateDisplay: '18-23 FEB 1946',
    datePrecision: 'exact',
    chronologicalPosition: 1,
    journeyStage: 'Freedom Movement',
    significance: 'Accelerated British realization that they could no longer rely on the Indian armed forces to maintain control.',
    category: 'Military & Political',
    domain: 'Military & Political',
    relatedPlaces: ['Bombay', 'Karachi', 'Madras'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-rin-mutiny',
    region: 'Bombay (and pan-India ports)',
    geographicRegion: 'Maharashtra, Sindh, Bengal',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-rin-mutiny', title: 'Mutiny in the Royal Indian Navy', authorOrInstitution: 'National Archives of India / Abhilekh Patal', yearOrPeriod: '1946', sourceType: 'government_archive', confidence: 'verified' }],
  },
  {
    id: 'event-tebhaga-movement-1946',
    decadeId: '1940s',
    year: 1946,
    title: 'Tebhaga Movement',
    subtitle: "Sharecroppers' struggle in Bengal",
    shortDescription: 'A significant peasant movement in Bengal demanding two-thirds of the harvest share.',
    fullDescription: 'Led by the Kisan Sabha, sharecroppers (bargadars) in Bengal revolted against the oppressive jotedari system. They demanded that their share of the harvest be increased from one-half to two-thirds (Tebhaga). The movement saw massive participation from rural women and marginalized castes.',
    era: '1946',
    dateDisplay: 'LATE 1946 - 1947',
    datePrecision: 'range',
    chronologicalPosition: 2,
    journeyStage: 'Agrarian Movements',
    significance: 'Highlighted the deep agrarian distress in rural Bengal and shaped post-independence land reform debates.',
    category: 'Agriculture & Social',
    domain: 'Agriculture & Social',
    organisations: ['All India Kisan Sabha'],
    relatedPlaces: ['Bengal'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-tebhaga-movement',
    region: 'Bengal',
    geographicRegion: 'Bengal',
    location: 'Rural Bengal',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-tebhaga', title: 'Agrarian Struggles in Bengal', authorOrInstitution: 'National Archives of India', yearOrPeriod: '1946', sourceType: 'government_archive', confidence: 'verified' }],
  },
  {
    id: 'event-constitution-1949',
    decadeId: '1940s',
    year: 1949,
    startDate: '1949-11-26',
    title: 'Adoption of the Constitution',
    subtitle: 'The Constituent Assembly',
    shortDescription: 'The Constituent Assembly adopted the Constitution of India, establishing a sovereign democratic republic.',
    fullDescription: 'After nearly three years of rigorous debate, the Constituent Assembly of India formally adopted the Constitution on November 26, 1949 (now celebrated as Constitution Day). The document laid the foundation for the world\\'s largest democracy with universal adult franchise, fundamental rights, and a federal structure.',
    era: '1949',
    dateDisplay: '26 NOV 1949',
    datePrecision: 'exact',
    chronologicalPosition: 3,
    journeyStage: 'Republic',
    significance: 'Established the legal and democratic framework for the modern Indian state.',
    category: 'Law & Governance',
    domain: 'Law & Governance',
    organisations: ['Constituent Assembly of India'],
    relatedPeople: ['B.R. Ambedkar', 'Rajendra Prasad', 'Jawaharlal Nehru', 'B.N. Rau'],
    relatedPlaces: ['New Delhi'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-constitution-1949',
    region: 'National',
    geographicRegion: 'Delhi (National)',
    location: 'Central Hall of Parliament, New Delhi',
    longTermSignificance: 'Provided a robust constitutional framework that has endured and evolved over decades.',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-constituent-assembly', title: 'Constituent Assembly Debates', authorOrInstitution: 'Parliament of India', yearOrPeriod: '1949', sourceType: 'government_archive', confidence: 'verified', url: 'https://loksabha.nic.in/debates/cadebates.aspx' }],
  },

  // -- 2010s -------------------------------------------------------------
  {
    id: 'event-mangalyaan-2014',
    decadeId: '2010s',
    year: 2014,
    startDate: '2014-09-24',
    title: 'Mangalyaan Enters Mars Orbit',
    subtitle: 'Mars Orbiter Mission Success',
    shortDescription: 'India became the first nation to successfully reach Mars orbit on its maiden attempt.',
    fullDescription: 'ISRO\\'s Mars Orbiter Mission (MOM), informally known as Mangalyaan, successfully entered Martian orbit on September 24, 2014. Developed with remarkable cost-efficiency, the mission made India the fourth space agency in the world to reach Mars and the first to do so on its very first try.',
    era: '2014',
    dateDisplay: '24 SEP 2014',
    datePrecision: 'exact',
    chronologicalPosition: 1,
    journeyStage: 'Science & Space',
    significance: 'Demonstrated India\\'s growing technological capabilities and self-reliance in interplanetary space exploration.',
    category: 'Science & Technology',
    domain: 'Science & Technology',
    organisations: ['ISRO'],
    relatedPlaces: ['Bengaluru', 'Sriharikota'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-mangalyaan',
    region: 'Bengaluru (Mission Control)',
    geographicRegion: 'Karnataka',
    location: 'Mars Orbit',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-isro-mom', title: 'Mars Orbiter Mission', authorOrInstitution: 'Indian Space Research Organisation (ISRO)', yearOrPeriod: '2014', sourceType: 'government_archive', confidence: 'verified', url: 'https://www.isro.gov.in/MarsOrbiterMission.html' }],
  },
  {
    id: 'event-gst-2017',
    decadeId: '2010s',
    year: 2017,
    startDate: '2017-07-01',
    title: 'Implementation of GST',
    subtitle: 'Goods and Services Tax',
    shortDescription: 'India rolled out a comprehensive indirect tax reform, unifying the national market.',
    fullDescription: 'At midnight on July 1, 2017, the Goods and Services Tax (GST) was launched in India. It replaced a complex web of central and state indirect taxes, implementing the vision of \\'One Nation, One Tax\\'. The reform represented the most significant fiscal restructuring in India since independence.',
    era: '2017',
    dateDisplay: '01 JUL 2017',
    datePrecision: 'exact',
    chronologicalPosition: 2,
    journeyStage: 'Economy',
    significance: 'Overhauled India\\'s indirect tax structure, formalizing the economy and unifying interstate trade.',
    category: 'Economy',
    domain: 'Economy',
    organisations: ['Ministry of Finance', 'GST Council'],
    relatedPlaces: ['New Delhi'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-gst',
    region: 'National',
    geographicRegion: 'National',
    location: 'New Delhi',
    longTermSignificance: 'Digitized and formalized tax compliance across the entire country.',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-gst-council', title: 'About GST', authorOrInstitution: 'GST Council, Ministry of Finance', yearOrPeriod: '2017', sourceType: 'government_archive', confidence: 'verified', url: 'https://gstcouncil.gov.in/' }],
  },
  {
    id: 'event-section-377-2018',
    decadeId: '2010s',
    year: 2018,
    startDate: '2018-09-06',
    title: 'Decriminalization of Section 377',
    subtitle: 'Navtej Singh Johar v. Union of India',
    shortDescription: 'The Supreme Court of India struck down the colonial-era law criminalizing consensual homosexual acts.',
    fullDescription: 'In a historic, unanimous verdict, a five-judge Constitution Bench of the Supreme Court of India read down Section 377 of the Indian Penal Code. The ruling declared that the criminalization of consensual same-sex relations was unconstitutional, citing violations of the right to equality, dignity, and privacy.',
    era: '2018',
    dateDisplay: '06 SEP 2018',
    datePrecision: 'exact',
    chronologicalPosition: 3,
    journeyStage: 'Law & Society',
    significance: 'A landmark victory for human rights and LGBTQ+ equality in India, overturning a 157-year-old colonial law.',
    category: 'Law & Governance',
    domain: 'Law & Governance',
    organisations: ['Supreme Court of India'],
    relatedPlaces: ['New Delhi'],
    relatedCivilizationIds: [],
    learningExperienceId: 'exp-section-377',
    region: 'National',
    geographicRegion: 'Delhi (National)',
    location: 'Supreme Court of India, New Delhi',
    masteryPercent: 0,
    isWeakConcept: false,
    experiences: [],
    sources: [{ id: 'src-sc-377', title: 'Navtej Singh Johar & Ors. v. Union of India', authorOrInstitution: 'Supreme Court of India', yearOrPeriod: '2018', sourceType: 'government_archive', confidence: 'verified', url: 'https://main.sci.gov.in/supremecourt/2016/14961/14961_2016_Judgement_06-Sep-2018.pdf' }],
  },
"""

experiences_to_add = """
  // -- 1890s -------------------------------------------------------------
  {
    id: 'exp-vivekananda-chicago',
    topicId: 'event-vivekananda-chicago-1893',
    title: 'Swami Vivekananda at Chicago',
    mode: 'story',
    estimatedMinutes: 5,
    difficulty: 'Introductory',
    summary: "Discover Swami Vivekananda's historic speech at the Parliament of the World's Religions.",
    learningObjectives: [
      'Understand the significance of the 1893 Parliament of Religions.',
      'Analyze the core message of universal tolerance in Vedanta.',
    ],
    historicalContext: 'Held in conjunction with the Columbian Exposition in Chicago, the Parliament brought together representatives of global faiths.',
    video: { title: 'Sisters and Brothers of America', durationSeconds: 60, posterLabel: 'A 2D story placeholder for Vivekananda in Chicago.', status: 'planned' },
    recapPoints: [
      "Vivekananda represented Hinduism in Chicago.",
      "He emphasized universal acceptance and tolerance.",
      "The event elevated Indian philosophical thought globally."
    ],
    sources: [{ id: 'src-vivekananda-chicago', title: 'Addresses at The Parliament of Religions', authorOrInstitution: 'Belur Math / Ramakrishna Mission', yearOrPeriod: '1893', sourceType: 'primary', confidence: 'verified', url: 'https://belurmath.org/swami-vivekananda-speeches-at-the-parliament-of-religions-chicago-1893/' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'Sisters and Brothers of America',
        narrative: 'When Swami Vivekananda stepped to the podium on September 11, 1893, his opening words broke convention. Instead of a formal academic greeting, he addressed the crowd as "Sisters and Brothers of America," receiving a two-minute standing ovation.',
        historicalEvidence: 'Archival records of the Parliament detail the unprecedented audience response to his opening remarks.',
        videos: [{ id: 'vid-viv-1', title: 'The Address', durationSeconds: 45, posterLabel: '2D Placeholder: The crowded hall of the Art Institute of Chicago.', status: 'planned' }],
        takeaway: 'A universal approach to humanity can bridge profound cultural divides.',
      },
      {
        stepNumber: 2,
        title: 'The Message of Universal Tolerance',
        narrative: 'In his addresses, he argued against sectarianism and bigotry, quoting the Gita to explain that all religious paths ultimately lead to the same truth.',
        historicalEvidence: 'The transcribed speeches published by the Ramakrishna Mission preserve his philosophical arguments.',
        takeaway: 'Vedantic philosophy provided a framework for religious pluralism.',
      }
    ],
  },
  {
    id: 'exp-epidemic-act',
    topicId: 'event-epidemic-act-1897',
    title: 'The Epidemic Diseases Act, 1897',
    mode: 'discover',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    summary: 'Investigate the colonial response to the Bombay plague and its societal fallout.',
    learningObjectives: [
      'Examine the provisions of the Epidemic Diseases Act.',
      'Understand the socio-political reaction to forced quarantines in Pune.',
    ],
    historicalContext: 'The third plague pandemic reached Bombay in 1896, prompting draconian public health measures by the British.',
    video: { title: 'The Plague and the Law', durationSeconds: 70, posterLabel: 'A 2D story placeholder for colonial Bombay and Pune.', status: 'planned' },
    recapPoints: [
      'The Act gave government sweeping powers to inspect and quarantine.',
      'Military enforcement in Pune deeply alienated the local population.',
      'It led to the assassination of W.C. Rand in 1897.'
    ],
    sources: [{ id: 'src-epidemic-act', title: 'The Epidemic Diseases Act, 1897', authorOrInstitution: 'India Code', yearOrPeriod: '1897', sourceType: 'government_archive', confidence: 'verified', url: 'https://www.indiacode.nic.in/handle/123456789/2330' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'Sweeping Powers',
        narrative: 'To combat the rapidly spreading bubonic plague, the colonial government hastily drafted the Epidemic Diseases Act. It allowed authorities to forcibly inspect homes, segregate patients, and destroy infected property.',
        historicalEvidence: 'The Act is preserved in the India Code, showing its brief but highly authoritative legal structure.',
        videos: [{ id: 'vid-epa-1', title: 'Drafting the Act', durationSeconds: 50, posterLabel: '2D Placeholder: Colonial officials drafting legislation.', status: 'planned' }],
        takeaway: 'Public health crises often lead to the rapid expansion of state power.',
      },
      {
        stepNumber: 2,
        title: 'The Pune Assassination',
        narrative: 'Under Commissioner W.C. Rand, British troops violently enforced plague regulations in Pune, violating cultural and religious sensitivities. In retaliation, the Chapekar brothers assassinated Rand on June 22, 1897.',
        historicalEvidence: 'Trial records and contemporary newspaper reports document the severe public backlash and the subsequent assassination.',
        takeaway: 'Insensitive administrative enforcement can trigger violent political resistance.',
      }
    ],
  },
  {
    id: 'exp-birsa-munda',
    topicId: 'event-birsa-munda-1899',
    title: "Birsa Munda's Ulgulan",
    mode: 'discover',
    estimatedMinutes: 6,
    difficulty: 'Intermediate',
    summary: 'Trace the roots of the tribal uprising in Chotanagpur against colonial exploitation.',
    learningObjectives: [
      'Understand the disruption of the Khuntkatti system.',
      'Analyze the leadership of Birsa Munda in mobilizing the tribal population.',
    ],
    historicalContext: 'British land policies allowed outsiders (dikus) to exploit tribal populations, eroding traditional community land ownership.',
    video: { title: 'The Great Tumult', durationSeconds: 75, posterLabel: 'A 2D story placeholder for the Chotanagpur landscape.', status: 'planned' },
    recapPoints: [
      'The Ulgulan was driven by agrarian exploitation and cultural intrusion.',
      'Birsa Munda unified the tribes under a new politico-religious vision.',
      'The rebellion resulted in the protective Chota Nagpur Tenancy Act.'
    ],
    sources: [{ id: 'src-birsa-munda', title: 'Tribal Resistance Movements', authorOrInstitution: 'National Archives of India', yearOrPeriod: '1899', sourceType: 'government_archive', confidence: 'verified' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'Loss of Khuntkatti',
        narrative: 'The traditional Munda system of joint landholding (Khuntkatti) was dismantled by British policies, replacing tribal owners with non-tribal landlords (zamindars) and moneylenders who extracted heavy rents.',
        historicalEvidence: 'Revenue records in the National Archives detail the rapid transfer of land titles away from indigenous communities.',
        videos: [{ id: 'vid-bm-1', title: 'The Dikus Arrive', durationSeconds: 55, posterLabel: '2D Placeholder: Agrarian conflict in 19th-century Jharkhand.', status: 'planned' }],
        takeaway: 'Economic dispossession is often the primary driver of agrarian revolts.',
      },
      {
        stepNumber: 2,
        title: 'The Ulgulan Begins',
        narrative: 'Birsa Munda called for an Ulgulan (Great Tumult) in late 1899, organizing guerilla attacks on police stations, churches, and landlord properties using traditional weapons.',
        historicalEvidence: 'British military dispatches from Ranchi recorded the widespread coordination and scale of the tribal attacks.',
        takeaway: 'Charismatic leadership can unite fragmented groups into a formidable resistance movement.',
      }
    ],
  },

  // -- 1940s -------------------------------------------------------------
  {
    id: 'exp-rin-mutiny',
    topicId: 'event-rin-mutiny-1946',
    title: 'Royal Indian Navy Mutiny',
    mode: 'reconstruct',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    summary: 'Examine the naval uprising that shook the foundation of the British Raj.',
    learningObjectives: [
      'Identify the causes of the naval mutiny.',
      'Understand its rapid spread and political impact.',
    ],
    historicalContext: 'Post-WWII India was highly volatile, marked by the INA trials and widespread anti-British sentiment.',
    video: { title: 'Mutiny on the Docks', durationSeconds: 80, posterLabel: 'A 2D story placeholder for ships in Bombay harbor.', status: 'planned' },
    recapPoints: [
      'The strike began on HMIS Talwar over poor food and racist abuse.',
      'It quickly became a mass anti-colonial uprising involving 20,000 sailors.',
      'It demonstrated that the British could no longer control the military.'
    ],
    sources: [{ id: 'src-rin-mutiny', title: 'Mutiny in the Royal Indian Navy', authorOrInstitution: 'National Archives of India / Abhilekh Patal', yearOrPeriod: '1946', sourceType: 'government_archive', confidence: 'verified' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'The Spark on HMIS Talwar',
        narrative: 'On February 18, 1946, ratings on the signals training ship HMIS Talwar went on hunger strike. The immediate trigger was unpalatable food and deeply racist insults from British commanding officers.',
        historicalEvidence: 'Declassified naval inquiry reports confirm the widespread grievances regarding rations and racial discrimination.',
        videos: [{ id: 'vid-rin-1', title: 'The Strike Begins', durationSeconds: 45, posterLabel: '2D Placeholder: Sailors refusing rations on the mess deck.', status: 'planned' }],
        takeaway: 'Institutionalized racism and poor conditions can ignite broader political rebellions.',
      },
      {
        stepNumber: 2,
        title: 'A Subcontinent in Revolt',
        narrative: 'Within 48 hours, the mutiny spread to 78 ships and 20 shore establishments. Ratings raised the flags of the Congress, Muslim League, and Communist Party together, showing unprecedented unity.',
        historicalEvidence: 'Archival photographs show ships in Bombay and Karachi flying combined flags of Indian political parties.',
        takeaway: 'Military uprisings have the power to rapidly accelerate the collapse of colonial authority.',
      }
    ],
  },
  {
    id: 'exp-tebhaga-movement',
    topicId: 'event-tebhaga-movement-1946',
    title: 'Tebhaga Movement',
    mode: 'discover',
    estimatedMinutes: 5,
    difficulty: 'Introductory',
    summary: "Follow the sharecroppers' struggle in Bengal for a fairer share of the harvest.",
    learningObjectives: [
      'Understand the jotedar-bargadar agrarian system.',
      'Analyze the impact of peasant mobilization on land reform.',
    ],
    historicalContext: 'Bengal in 1946 was recovering from a devastating famine, sharpening the conflict between landowners and peasants.',
    video: { title: 'The Cry for Tebhaga', durationSeconds: 65, posterLabel: 'A 2D story placeholder for rural Bengal paddy fields.', status: 'planned' },
    recapPoints: [
      'Sharecroppers demanded a two-thirds share of the harvest.',
      'The movement challenged the oppressive jotedar landlords.',
      'It laid the groundwork for post-independence land reforms.'
    ],
    sources: [{ id: 'src-tebhaga', title: 'Agrarian Struggles in Bengal', authorOrInstitution: 'National Archives of India', yearOrPeriod: '1946', sourceType: 'government_archive', confidence: 'verified' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'The Two-Thirds Demand',
        narrative: 'Sharecroppers (bargadars) traditionally surrendered half their crop to the landlords (jotedars). In late 1946, guided by the Floud Commission report, they demanded \'Tebhaga\'—retaining two-thirds of the harvest for themselves.',
        historicalEvidence: 'The Floud Commission (Land Revenue Commission of Bengal, 1940) officially recommended the two-thirds share.',
        videos: [{ id: 'vid-teb-1', title: 'Harvesting the Demand', durationSeconds: 50, posterLabel: '2D Placeholder: Peasants gathering grain at the threshing floor.', status: 'planned' }],
        takeaway: 'Official government reports can legitimize grassroots demands for economic justice.',
      }
    ],
  },
  {
    id: 'exp-constitution-1949',
    topicId: 'event-constitution-1949',
    title: 'Adoption of the Constitution',
    mode: 'story',
    estimatedMinutes: 6,
    difficulty: 'Intermediate',
    summary: 'Witness the conclusion of the Constituent Assembly and the birth of a Republic.',
    learningObjectives: [
      'Understand the drafting process of the Indian Constitution.',
      'Appreciate the scale of establishing universal adult franchise.',
    ],
    historicalContext: 'Drafted amidst the trauma of Partition, the Constitution sought to unify a deeply diverse and socially stratified subcontinent.',
    video: { title: 'We, the People', durationSeconds: 90, posterLabel: 'A 2D story placeholder for the Constituent Assembly hall.', status: 'planned' },
    recapPoints: [
      'The Assembly debated the draft for nearly three years.',
      'The Constitution established a sovereign, democratic republic.',
      'It formally enshrined fundamental rights and universal franchise.'
    ],
    sources: [{ id: 'src-constituent-assembly', title: 'Constituent Assembly Debates', authorOrInstitution: 'Parliament of India', yearOrPeriod: '1949', sourceType: 'government_archive', confidence: 'verified', url: 'https://loksabha.nic.in/debates/cadebates.aspx' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'The Final Draft',
        narrative: 'On November 26, 1949, Dr. B.R. Ambedkar presented the final draft of the Constitution. In his closing speech, he warned that political democracy must be accompanied by social democracy to survive.',
        historicalEvidence: 'The Constituent Assembly Debates perfectly preserve Ambedkar\\'s "Grammar of Anarchy" speech.',
        videos: [{ id: 'vid-const-1', title: 'Ambedkar\\'s Warning', durationSeconds: 65, posterLabel: '2D Placeholder: Dr. Ambedkar addressing the Assembly.', status: 'planned' }],
        takeaway: 'A constitution provides the legal machinery, but social equality requires active societal commitment.',
      }
    ],
  },

  // -- 2010s -------------------------------------------------------------
  {
    id: 'exp-mangalyaan',
    topicId: 'event-mangalyaan-2014',
    title: 'Mangalyaan Enters Mars Orbit',
    mode: 'discover',
    estimatedMinutes: 4,
    difficulty: 'Introductory',
    summary: 'Relive the historic moment ISRO successfully inserted a probe into Martian orbit.',
    learningObjectives: [
      'Understand the technological achievement of the Mars Orbiter Mission.',
      'Recognize the efficiency and cost-effectiveness of ISRO\\'s approach.',
    ],
    historicalContext: 'Space exploration was traditionally dominated by the US, Russia, and the ESA. India\\'s mission was highly scrutinized for its low budget.',
    video: { title: 'First Attempt Success', durationSeconds: 55, posterLabel: 'A 2D story placeholder for MOM in orbit.', status: 'planned' },
    recapPoints: [
      'India was the first nation to succeed on its first Mars attempt.',
      'The mission cost only $74 million.',
      'It demonstrated highly precise orbital mechanics and engineering.'
    ],
    sources: [{ id: 'src-isro-mom', title: 'Mars Orbiter Mission', authorOrInstitution: 'Indian Space Research Organisation (ISRO)', yearOrPeriod: '2014', sourceType: 'government_archive', confidence: 'verified', url: 'https://www.isro.gov.in/MarsOrbiterMission.html' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'The Slingshot to Mars',
        narrative: 'Because the PSLV rocket lacked the thrust to send the probe directly to Mars, ISRO engineers utilized a series of Earth-bound maneuvers to build momentum before executing a highly precise trans-Martian injection.',
        historicalEvidence: 'ISRO\\'s mission telemetry and trajectory logs confirm the use of the Hohmann transfer orbit strategy.',
        videos: [{ id: 'vid-mom-1', title: 'Orbital Slingshot', durationSeconds: 40, posterLabel: '2D Placeholder: Diagram of Earth-bound maneuvers.', status: 'planned' }],
        takeaway: 'Resource constraints can drive innovative engineering solutions.',
      }
    ],
  },
  {
    id: 'exp-gst',
    topicId: 'event-gst-2017',
    title: 'Implementation of GST',
    mode: 'reconstruct',
    estimatedMinutes: 5,
    difficulty: 'Intermediate',
    summary: 'Analyze the rollout of the Goods and Services Tax and its impact on the Indian economy.',
    learningObjectives: [
      'Understand the complexity of pre-2017 indirect taxation.',
      'Evaluate the mechanism and goals of the GST framework.',
    ],
    historicalContext: 'Before GST, moving goods across Indian state borders required paying multiple overlapping taxes, heavily fragmenting the national market.',
    video: { title: 'One Nation, One Tax', durationSeconds: 60, posterLabel: 'A 2D story placeholder for trade networks.', status: 'planned' },
    recapPoints: [
      'GST replaced multiple state and central taxes.',
      'It aimed to create a unified national market.',
      'The transition required immense digital infrastructure (GSTN).'
    ],
    sources: [{ id: 'src-gst-council', title: 'About GST', authorOrInstitution: 'GST Council, Ministry of Finance', yearOrPeriod: '2017', sourceType: 'government_archive', confidence: 'verified', url: 'https://gstcouncil.gov.in/' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'Unifying the Market',
        narrative: 'At midnight on July 1, 2017, the GST was enacted through a special session of Parliament. It subsumed excise duties, VAT, octroi, and service tax into a single multi-tier tax system.',
        historicalEvidence: 'The 101st Amendment of the Constitution of India provides the legal basis for the GST rollout.',
        videos: [{ id: 'vid-gst-1', title: 'Removing Checkposts', durationSeconds: 50, posterLabel: '2D Placeholder: Trucks moving freely across state borders.', status: 'planned' }],
        takeaway: 'Major economic reforms require constitutional amendments and federal consensus.',
      }
    ],
  },
  {
    id: 'exp-section-377',
    topicId: 'event-section-377-2018',
    title: 'Decriminalization of Section 377',
    mode: 'story',
    estimatedMinutes: 6,
    difficulty: 'Advanced',
    summary: 'Read how the Supreme Court struck down a 157-year-old colonial law to protect LGBTQ+ rights.',
    learningObjectives: [
      'Understand the constitutional arguments against Section 377.',
      'Analyze the role of the judiciary in protecting minority rights.',
    ],
    historicalContext: 'Section 377 was introduced by the British in 1861, imposing Victorian morality on the subcontinent and criminalizing the LGBTQ+ community for over a century.',
    video: { title: 'The Arc of Justice', durationSeconds: 85, posterLabel: 'A 2D story placeholder for the Supreme Court ruling.', status: 'planned' },
    recapPoints: [
      'A five-judge Constitution Bench ruled unanimously.',
      'The judgment affirmed that sexual orientation is natural and innate.',
      'It apologized for the historical wrongs committed against the community.'
    ],
    sources: [{ id: 'src-sc-377', title: 'Navtej Singh Johar & Ors. v. Union of India', authorOrInstitution: 'Supreme Court of India', yearOrPeriod: '2018', sourceType: 'government_archive', confidence: 'verified', url: 'https://main.sci.gov.in/supremecourt/2016/14961/14961_2016_Judgement_06-Sep-2018.pdf' }],
    status: 'unlocked',
    xpReward: 0,
    subtopics: [
      {
        stepNumber: 1,
        title: 'Constitutional Morality',
        narrative: 'Chief Justice Dipak Misra declared, "I am what I am, so take me as I am." The Court ruled that constitutional morality must trump social morality, ensuring that fundamental rights are not subjected to majoritarian views.',
        historicalEvidence: 'The 493-page Supreme Court judgment extensively cites the Right to Privacy, Dignity, and Equality (Articles 14, 15, and 21).',
        videos: [{ id: 'vid-377-1', title: 'Reading the Verdict', durationSeconds: 60, posterLabel: '2D Placeholder: Jubilation outside the Supreme Court.', status: 'planned' }],
        takeaway: 'The Constitution exists to protect the rights of minorities against the prejudices of the majority.',
      }
    ],
  },
"""

with open('src/data/topics.ts', 'r') as f:
    topics_content = f.read()

# Add topics before the end of the array
if "event-vivekananda-chicago-1893" not in topics_content:
    topics_content = topics_content.replace('];\n', topics_to_add + '];\n')
    with open('src/data/topics.ts', 'w') as f:
        f.write(topics_content)


with open('src/data/experiences.ts', 'r') as f:
    exp_content = f.read()

if "exp-vivekananda-chicago" not in exp_content:
    exp_content = exp_content.replace('];\n', experiences_to_add + '];\n')
    with open('src/data/experiences.ts', 'w') as f:
        f.write(exp_content)

print('Injection done')
